sudo: false
language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  - IDEA_VERSION=IC-15.0.4

#env:
#  global:
  # JetBrains plugin release credentials
  # JETBRAINS_USER
  #- secure: ...
  # JETBRAINS_PASS
  #- secure: ...

before_script:
 - chmod +x gradlew

script:
- ./gradlew buildPlugin -PideaVersion=$IDEA_VERSION